#!/usr/bin/env bash
# Script to install nginx:
sudo apt-get -y update
sudo apt-get -y install nginx
# sudo chown -R ubuntu <path_carpeta>
echo 'Holberton School' > /var/www/html/index.nginx-debian.html
sudo service nginx start
