#!/usr/bin/env bash
# Script to install nginx:
sudo apt-get -y update
sudo apt-get -y install nginx
# sudo chown -R ubuntu <path_carpeta>
echo 'Holberton School' > /var/www/html/index.nginx-debian.html
sudo service nginx start
new_string="server_name _;\n\t\trewrite ^\/redirect_me$ https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
sed -i "s/server_name _;/$new_string/g" /etc/nginx/sites-available/default
sudo service nginx restart
