#!/usr/bin/env bash
# Script to install nginx:
sudo apt-get -y update
sudo apt-get -y install nginx
sudo chown -R ubuntu /var/www/html/
echo 'Holberton School' > /var/www/html/index.nginx-debian.html
sudo service nginx start
# Redireccion to youtube
new_string="server_name _;\n\t\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s/server_name _;/$new_string/g" /etc/nginx/sites-available/default
# Redirection the error 404
echo "Ceci n'est pas une page" >> /var/www/html/error404.html
new_string="server_name _;\n\terror_page 404 \/error404.html;"
sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-available/default

#Aply changes on nginx
sudo service nginx restart
