#!/usr/bin/env bash
# setting a new load balancer
sudo apt-get update
sudo apt-get install haproxy -y
sudo chmod 777 /etc/default/haproxy
sudo echo "ENABLED=1" >> /etc/default/haproxy
sudo chmod 777 /etc/haproxy/haproxy.cfg
sudo printf "\nfrontend http_front\n\tbind *:80\n\tdefault_backend http_back\n" >> /etc/haproxy/haproxy.cfg
sudo printf "\nbackend http_back\n\tbalance roundrobin\n\tserver web-01 34.73.50.135:80 check\n\tserver web-02 52.73.46.71:80 check" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
