#!/usr/bin/env bash
# Bash script infinit loop with To infinity and beyond and I am invincible!!! when catch SIGTERM
trap "echo I am invincible!!!" SIGTERM
while true
do 
    echo "To infinity and beyond"
    sleep 2
done