#!/usr/bin/env bash
# Bash script that displays Holberton School 10 times
# and if 9 display 'hi'

i=0
while [ $i -le 9 ]
do
	if [[ $i -eq 9 ]]; then echo "Hi"; fi
	echo "Holberton School"
	i=$((i + 1))
done
