#!/usr/bin/env bash
# Bash script that displays Holberton School 10 times
# and displays bad luck for the 4th loop iteration
# and displays good luck for the 8th loop iteration

i=0

while [ $i -le 9 ]
do
	if [[ $i -eq 3 ]]; then echo "bad luck";
	elif [[ $i -eq 7 ]]; then echo "good luck";
	else echo "Holberton School"; fi
	i=$((i + 1))
done
