#!/usr/bin/env bash
#this script displaying "Holberton School" 10 times
#and say bad luck for the 4th loop iteration and good luck for the 8th loop iteration

i=1
while [ $i -lt 11 ]
do
	if [ "$i" == "4" ]; then
		echo "bad luck"
	elif [ "$i" == "8" ]; then
		echo "good luck"
	else
		echo "Holberton School"
	fi
	let i=i+1
done
