#!/usr/bin/env bash
# This script displaying the thime for 12 hours and 59 minutes

hours=0
minutes=1
while [ $hours -lt 13 ]
do
	echo "Hour: $hours"
	while [ $minutes -lt 60 ]
	do
		echo "$minutes"
		let minutes+=1
	done
	let hours+=1
	minutes=1
done
