#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes:
hours=0
minu=1

while [ $hours -le 12 ]
do
	echo "Hour: "$hours
	while [ $minu -le 59 ]
	do
		echo $minu
		minu=$((minu + 1))
	done
hours=$((hours + 1))
minu=0
done
