#!/usr/bin/env bash
# This script that gives you information about the holbertonschool file.

name=holbertonschool
if [ -e $name ] ; then
	echo "holbertonschool file exists"

	if [ -s $name ] ; then
		echo "holbertonschool file is not empty"
	else
		echo "holbertonschool file is empty"
	fi
	if [ -f $name ] ; then
		echo "holbertonschool is a regular file"
	fi
else
	echo "holbertonschool file does not exist"
fi
