#!/usr/bin/env bash
# Bash script that configures an Ubuntu server 

cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/g' ~/hosts.new
echo -e "8.8.8.8\tfacebook.com" >> ~/hosts.new
cat ~/hosts.new > /etc/hosts
